sudo: false

cache:
  directories:
    - .cabal-sandbox
    - imperative-edsl
    - feldspar-language
    - feldspar-compiler

language: haskell

ghc:
  - 7.8
  - 7.6
  - 7.4

before_install:
  - cabal install cabal-install-1.20.0.6
  - cabal install alex happy
  - cabal sandbox init
  - if [ ! -d imperative-edsl/.git ]; then rm -rf imperative-edsl && git clone https://github.com/emilaxelsson/imperative-edsl; fi
  - if [ ! -d feldspar-language/.git ]; then rm -rf feldspar-language && git clone https://github.com/Feldspar/feldspar-language; fi
  - if [ ! -d feldspar-compiler/.git ]; then rm -rf feldspar-compiler && git clone https://github.com/Feldspar/feldspar-compiler; fi
  - cd $TRAVIS_BUILD_DIR/imperative-edsl   && git fetch -v && git checkout $TRAVIS_BRANCH || git checkout master
  - cd $TRAVIS_BUILD_DIR/feldspar-language && git fetch -v && git checkout $TRAVIS_BRANCH || git checkout master
  - cd $TRAVIS_BUILD_DIR/feldspar-compiler && git fetch -v && git checkout $TRAVIS_BRANCH || git checkout master
  - cd $TRAVIS_BUILD_DIR
  - cabal sandbox add-source imperative-edsl
  - cabal sandbox add-source feldspar-language
  - cabal sandbox add-source feldspar-compiler
  - cabal sandbox hc-pkg dump
  - cabal install --enable-tests --only-dependencies --reinstall --upgrade-dependencies --dry-run -v2

install:
  - cabal install --enable-tests --only-dependencies --reinstall --upgrade-dependencies
